/*
* generated by Xtext
*/
package dk.sdu.mmmi.embedix;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ULSWIGUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return dk.sdu.mmmi.embedix.ui.internal.ULSWIGActivator.getInstance().getInjector("dk.sdu.mmmi.embedix.ULSWIG");
	}
	
}
