/*
 * generated by Xtext
 */
package dk.sdu.mmmi.embedix;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ULSWIGRuntimeModule extends dk.sdu.mmmi.embedix.AbstractULSWIGRuntimeModule {

}
