/*
* generated by Xtext
*/
package dk.sdu.mmmi.embedix.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import dk.sdu.mmmi.embedix.services.ULSWIGGrammarAccess;

public class ULSWIGParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ULSWIGGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected dk.sdu.mmmi.embedix.parser.antlr.internal.InternalULSWIGParser createParser(XtextTokenStream stream) {
		return new dk.sdu.mmmi.embedix.parser.antlr.internal.InternalULSWIGParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Robot";
	}
	
	public ULSWIGGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ULSWIGGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
