/*
 * generated by Xtext
 */
package dk.sdu.mmmi.embedix.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ULSWIGUiModule extends dk.sdu.mmmi.embedix.ui.AbstractULSWIGUiModule {
	public ULSWIGUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
