/*
 * generated by Xtext
 */
package dk.sdu.mmmi.embedix.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import dk.sdu.mmmi.embedix.ui.internal.ULSWIGActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ULSWIGExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ULSWIGActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ULSWIGActivator.getInstance().getInjector(ULSWIGActivator.DK_SDU_MMMI_EMBEDIX_ULSWIG);
	}
	
}
