/*
* generated by Xtext
*/
package dk.sdu.mmmi.embedix.ui.contentassist;

import dk.sdu.mmmi.embedix.ui.contentassist.AbstractULSWIGProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ULSWIGProposalProvider extends AbstractULSWIGProposalProvider {

}
