/*
* generated by Xtext
*/
package dk.sdu.mmmi.embedix.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import dk.sdu.mmmi.embedix.services.ULSWIGGrammarAccess;

public class ULSWIGParser extends AbstractContentAssistParser {
	
	@Inject
	private ULSWIGGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected dk.sdu.mmmi.embedix.ui.contentassist.antlr.internal.InternalULSWIGParser createParser() {
		dk.sdu.mmmi.embedix.ui.contentassist.antlr.internal.InternalULSWIGParser result = new dk.sdu.mmmi.embedix.ui.contentassist.antlr.internal.InternalULSWIGParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getConstructorAddressParametersAccess().getAlternatives(), "rule__ConstructorAddressParameters__Alternatives");
					put(grammarAccess.getMemberAccess().getAlternatives(), "rule__Member__Alternatives");
					put(grammarAccess.getLinkPropertyAccess().getAlternatives(), "rule__LinkProperty__Alternatives");
					put(grammarAccess.getExpansionAccess().getAlternatives(), "rule__Expansion__Alternatives");
					put(grammarAccess.getArgumentAccess().getAlternatives(), "rule__Argument__Alternatives");
					put(grammarAccess.getAddressSpecAccess().getAlternatives(), "rule__AddressSpec__Alternatives");
					put(grammarAccess.getKindAccess().getAlternatives(), "rule__Kind__Alternatives");
					put(grammarAccess.getInstantiationPropertyAccess().getAlternatives(), "rule__InstantiationProperty__Alternatives");
					put(grammarAccess.getPathElementAccess().getAlternatives(), "rule__PathElement__Alternatives");
					put(grammarAccess.getLinkSpecAccess().getGroup(), "rule__LinkSpec__Group__0");
					put(grammarAccess.getLinkSpecAccess().getGroup_1(), "rule__LinkSpec__Group_1__0");
					put(grammarAccess.getConstructorAccess().getGroup(), "rule__Constructor__Group__0");
					put(grammarAccess.getConstructorAccess().getGroup_3(), "rule__Constructor__Group_3__0");
					put(grammarAccess.getConstructorAccess().getGroup_3_1(), "rule__Constructor__Group_3_1__0");
					put(grammarAccess.getConstructorAccess().getGroup_5(), "rule__Constructor__Group_5__0");
					put(grammarAccess.getConstructorAccess().getGroup_7(), "rule__Constructor__Group_7__0");
					put(grammarAccess.getNamedAddressesAccess().getGroup(), "rule__NamedAddresses__Group__0");
					put(grammarAccess.getNamedAddressesAccess().getGroup_2(), "rule__NamedAddresses__Group_2__0");
					put(grammarAccess.getAddressTupleAccess().getGroup(), "rule__AddressTuple__Group__0");
					put(grammarAccess.getAddressTupleAccess().getGroup_3(), "rule__AddressTuple__Group_3__0");
					put(grammarAccess.getTosNetLinkBindingAccess().getGroup(), "rule__TosNetLinkBinding__Group__0");
					put(grammarAccess.getTosNetLinkBindingAccess().getGroup_3(), "rule__TosNetLinkBinding__Group_3__0");
					put(grammarAccess.getLinkPropertyAccess().getGroup_0(), "rule__LinkProperty__Group_0__0");
					put(grammarAccess.getLinkPropertyAccess().getGroup_1(), "rule__LinkProperty__Group_1__0");
					put(grammarAccess.getLinkPropertyAccess().getGroup_2(), "rule__LinkProperty__Group_2__0");
					put(grammarAccess.getSimpleExpansionAccess().getGroup(), "rule__SimpleExpansion__Group__0");
					put(grammarAccess.getSimpleExpansionAccess().getGroup_4(), "rule__SimpleExpansion__Group_4__0");
					put(grammarAccess.getSimpleExpansionAccess().getGroup_4_1(), "rule__SimpleExpansion__Group_4_1__0");
					put(grammarAccess.getSimpleExpansionAccess().getGroup_6(), "rule__SimpleExpansion__Group_6__0");
					put(grammarAccess.getSimpleExpansionAccess().getGroup_6_1(), "rule__SimpleExpansion__Group_6_1__0");
					put(grammarAccess.getAddressExpansionAccess().getGroup(), "rule__AddressExpansion__Group__0");
					put(grammarAccess.getAddressExpansionAccess().getGroup_5(), "rule__AddressExpansion__Group_5__0");
					put(grammarAccess.getAddressExpansionAccess().getGroup_5_1(), "rule__AddressExpansion__Group_5_1__0");
					put(grammarAccess.getArgumentAccess().getGroup_1(), "rule__Argument__Group_1__0");
					put(grammarAccess.getAddressBindingAccess().getGroup(), "rule__AddressBinding__Group__0");
					put(grammarAccess.getAddressBindingAccess().getGroup_1(), "rule__AddressBinding__Group_1__0");
					put(grammarAccess.getAddressBindingAccess().getGroup_4(), "rule__AddressBinding__Group_4__0");
					put(grammarAccess.getInstantiationAccess().getGroup(), "rule__Instantiation__Group__0");
					put(grammarAccess.getInstantiationAccess().getGroup_5(), "rule__Instantiation__Group_5__0");
					put(grammarAccess.getInstantiationAccess().getGroup_5_1(), "rule__Instantiation__Group_5_1__0");
					put(grammarAccess.getDirectAddressSpecAccess().getGroup(), "rule__DirectAddressSpec__Group__0");
					put(grammarAccess.getInstantiationPropertyAccess().getGroup_0(), "rule__InstantiationProperty__Group_0__0");
					put(grammarAccess.getInstantiationPropertyAccess().getGroup_1(), "rule__InstantiationProperty__Group_1__0");
					put(grammarAccess.getInstantiationPropertyAccess().getGroup_2(), "rule__InstantiationProperty__Group_2__0");
					put(grammarAccess.getGroupingAccess().getGroup(), "rule__Grouping__Group__0");
					put(grammarAccess.getGroupingAccess().getGroup_3(), "rule__Grouping__Group_3__0");
					put(grammarAccess.getGroupElementAccess().getGroup(), "rule__GroupElement__Group__0");
					put(grammarAccess.getGroupElementAccess().getGroup_1(), "rule__GroupElement__Group_1__0");
					put(grammarAccess.getPathElementAccess().getGroup_1(), "rule__PathElement__Group_1__0");
					put(grammarAccess.getLinkSpecAccess().getPackagenameAssignment_1_0(), "rule__LinkSpec__PackagenameAssignment_1_0");
					put(grammarAccess.getLinkSpecAccess().getNameAssignment_2(), "rule__LinkSpec__NameAssignment_2");
					put(grammarAccess.getLinkSpecAccess().getConstructorsAssignment_4(), "rule__LinkSpec__ConstructorsAssignment_4");
					put(grammarAccess.getConstructorAccess().getIsPublicAssignment_0(), "rule__Constructor__IsPublicAssignment_0");
					put(grammarAccess.getConstructorAccess().getNameAssignment_1(), "rule__Constructor__NameAssignment_1");
					put(grammarAccess.getConstructorAccess().getParametersAssignment_3_0(), "rule__Constructor__ParametersAssignment_3_0");
					put(grammarAccess.getConstructorAccess().getParametersAssignment_3_1_1(), "rule__Constructor__ParametersAssignment_3_1_1");
					put(grammarAccess.getConstructorAccess().getAddressesAssignment_5_1(), "rule__Constructor__AddressesAssignment_5_1");
					put(grammarAccess.getConstructorAccess().getMembersAssignment_7_0(), "rule__Constructor__MembersAssignment_7_0");
					put(grammarAccess.getNamedAddressesAccess().getAddressNamesAssignment_1(), "rule__NamedAddresses__AddressNamesAssignment_1");
					put(grammarAccess.getNamedAddressesAccess().getAddressNamesAssignment_2_2(), "rule__NamedAddresses__AddressNamesAssignment_2_2");
					put(grammarAccess.getAddressTupleAccess().getElementsAssignment_2(), "rule__AddressTuple__ElementsAssignment_2");
					put(grammarAccess.getAddressTupleAccess().getElementsAssignment_3_1(), "rule__AddressTuple__ElementsAssignment_3_1");
					put(grammarAccess.getTosNetLinkBindingAccess().getPropertiesAssignment_2(), "rule__TosNetLinkBinding__PropertiesAssignment_2");
					put(grammarAccess.getTosNetLinkBindingAccess().getPropertiesAssignment_3_1(), "rule__TosNetLinkBinding__PropertiesAssignment_3_1");
					put(grammarAccess.getLinkPropertyAccess().getCtrlNameAssignment_0_2(), "rule__LinkProperty__CtrlNameAssignment_0_2");
					put(grammarAccess.getLinkPropertyAccess().getBaseValueAssignment_1_2(), "rule__LinkProperty__BaseValueAssignment_1_2");
					put(grammarAccess.getLinkPropertyAccess().getUartNameAssignment_2_2(), "rule__LinkProperty__UartNameAssignment_2_2");
					put(grammarAccess.getSimpleExpansionAccess().getNameAssignment_0(), "rule__SimpleExpansion__NameAssignment_0");
					put(grammarAccess.getSimpleExpansionAccess().getConstructorAssignment_2(), "rule__SimpleExpansion__ConstructorAssignment_2");
					put(grammarAccess.getSimpleExpansionAccess().getArgumentsAssignment_4_0(), "rule__SimpleExpansion__ArgumentsAssignment_4_0");
					put(grammarAccess.getSimpleExpansionAccess().getArgumentsAssignment_4_1_1(), "rule__SimpleExpansion__ArgumentsAssignment_4_1_1");
					put(grammarAccess.getSimpleExpansionAccess().getBindingsAssignment_6_0(), "rule__SimpleExpansion__BindingsAssignment_6_0");
					put(grammarAccess.getSimpleExpansionAccess().getBindingsAssignment_6_1_1(), "rule__SimpleExpansion__BindingsAssignment_6_1_1");
					put(grammarAccess.getAddressExpansionAccess().getNameAssignment_1(), "rule__AddressExpansion__NameAssignment_1");
					put(grammarAccess.getAddressExpansionAccess().getConstructorAssignment_3(), "rule__AddressExpansion__ConstructorAssignment_3");
					put(grammarAccess.getAddressExpansionAccess().getArgumentsAssignment_5_0(), "rule__AddressExpansion__ArgumentsAssignment_5_0");
					put(grammarAccess.getAddressExpansionAccess().getArgumentsAssignment_5_1_1(), "rule__AddressExpansion__ArgumentsAssignment_5_1_1");
					put(grammarAccess.getArgumentAccess().getSimpleAssignment_0(), "rule__Argument__SimpleAssignment_0");
					put(grammarAccess.getArgumentAccess().getLhsAssignment_1_0(), "rule__Argument__LhsAssignment_1_0");
					put(grammarAccess.getArgumentAccess().getRhsAssignment_1_2(), "rule__Argument__RhsAssignment_1_2");
					put(grammarAccess.getArgumentAccess().getTextAssignment_2(), "rule__Argument__TextAssignment_2");
					put(grammarAccess.getAddressBindingAccess().getNameAssignment_1_0(), "rule__AddressBinding__NameAssignment_1_0");
					put(grammarAccess.getAddressBindingAccess().getAddressesAssignment_3(), "rule__AddressBinding__AddressesAssignment_3");
					put(grammarAccess.getAddressBindingAccess().getAddressesAssignment_4_1(), "rule__AddressBinding__AddressesAssignment_4_1");
					put(grammarAccess.getInstantiationAccess().getAddressAssignment_1(), "rule__Instantiation__AddressAssignment_1");
					put(grammarAccess.getInstantiationAccess().getKindAssignment_3(), "rule__Instantiation__KindAssignment_3");
					put(grammarAccess.getInstantiationAccess().getPropertiesAssignment_5_0(), "rule__Instantiation__PropertiesAssignment_5_0");
					put(grammarAccess.getInstantiationAccess().getPropertiesAssignment_5_1_1(), "rule__Instantiation__PropertiesAssignment_5_1_1");
					put(grammarAccess.getDirectAddressSpecAccess().getNameAssignment_0(), "rule__DirectAddressSpec__NameAssignment_0");
					put(grammarAccess.getDirectAddressSpecAccess().getAddressAssignment_2(), "rule__DirectAddressSpec__AddressAssignment_2");
					put(grammarAccess.getNamedAddressSpecAccess().getNameAssignment(), "rule__NamedAddressSpec__NameAssignment");
					put(grammarAccess.getInstantiationPropertyAccess().getIdAssignment_0_3(), "rule__InstantiationProperty__IdAssignment_0_3");
					put(grammarAccess.getInstantiationPropertyAccess().getModeAssignment_2_3(), "rule__InstantiationProperty__ModeAssignment_2_3");
					put(grammarAccess.getInstantiationPropertyAccess().getRateAssignment_2_5(), "rule__InstantiationProperty__RateAssignment_2_5");
					put(grammarAccess.getGroupingAccess().getNameAssignment_0(), "rule__Grouping__NameAssignment_0");
					put(grammarAccess.getGroupingAccess().getElementsAssignment_2(), "rule__Grouping__ElementsAssignment_2");
					put(grammarAccess.getGroupingAccess().getElementsAssignment_3_1(), "rule__Grouping__ElementsAssignment_3_1");
					put(grammarAccess.getGroupElementAccess().getPathAssignment_0(), "rule__GroupElement__PathAssignment_0");
					put(grammarAccess.getGroupElementAccess().getPathAssignment_1_1(), "rule__GroupElement__PathAssignment_1_1");
					put(grammarAccess.getPathElementAccess().getSimpleAssignment_0(), "rule__PathElement__SimpleAssignment_0");
					put(grammarAccess.getPathElementAccess().getTypeAssignment_1_2(), "rule__PathElement__TypeAssignment_1_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			dk.sdu.mmmi.embedix.ui.contentassist.antlr.internal.InternalULSWIGParser typedParser = (dk.sdu.mmmi.embedix.ui.contentassist.antlr.internal.InternalULSWIGParser) parser;
			typedParser.entryRuleLinkSpec();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ULSWIGGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ULSWIGGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
